//! Log file parser for tracing JSON output.
//!
//! Parses pretty-printed JSON logs generated by tracing-subscriber's JSON
//! writer. Each JSON object may span multiple lines with indentation. This
//! is the canonical log parser — moved here from context-stack's
//! `context-api` so `log-viewer` no longer needs a `context-api` dependency.

use once_cell::sync::Lazy;
use regex::Regex;
use serde::{
    Deserialize,
    Serialize,
};
use std::collections::HashMap;

// Regex to strip ANSI escape codes
static ANSI_REGEX: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"\x1b\[[0-9;]*m").unwrap());

// Regex to parse panic location from message: "panicked at <file>:<line>:<col>:"
static PANIC_LOCATION_REGEX: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"panicked at ([^:]+):(\d+):(\d+):").unwrap());

// Regex to parse assertion diff header
static ASSERTION_DIFF_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?s)assertion failed: `\(left == right\)`.*?Diff < (\w+) / (\w+) >\s*:\s*(.+)")
        .unwrap()
});

/// Strip ANSI escape codes from a string.
fn strip_ansi_codes(s: &str) -> String {
    ANSI_REGEX.replace_all(s, "").to_string()
}

/// Parse panic location from message like "panicked at file.rs:123:5: assertion..."
fn parse_panic_location(message: &str) -> Option<(String, u32, u32)> {
    PANIC_LOCATION_REGEX.captures(message).map(|caps| {
        let file = caps.get(1).unwrap().as_str().to_string();
        let line: u32 = caps.get(2).unwrap().as_str().parse().unwrap_or(0);
        let col: u32 = caps.get(3).unwrap().as_str().parse().unwrap_or(0);
        (file, line, col)
    })
}

/// Parsed assertion diff data.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, ts_rs::TS)]
pub struct AssertionDiff {
    pub title: String,
    pub left_label: String,
    pub right_label: String,
    pub left_value: String,
    pub right_value: String,
}

/// Parse assertion diff from message.
fn parse_assertion_diff(message: &str) -> Option<AssertionDiff> {
    let captures = ASSERTION_DIFF_REGEX.captures(message)?;
    let left_label = captures.get(1)?.as_str().to_string();
    let right_label = captures.get(2)?.as_str().to_string();
    let diff_content = captures.get(3)?.as_str();

    let mut left_lines = Vec::new();
    let mut right_lines = Vec::new();

    for line in diff_content.lines() {
        if let Some(rest) = line.strip_prefix('<') {
            left_lines.push(rest.to_string());
        } else if let Some(rest) = line.strip_prefix('>') {
            right_lines.push(rest.to_string());
        }
    }

    Some(AssertionDiff {
        title: "assertion failed: `(left == right)`".to_string(),
        left_label,
        right_label,
        left_value: left_lines.join("\n"),
        right_value: right_lines.join("\n"),
    })
}

/// A parsed log entry — the full representation with all fields.
///
/// This is the canonical log entry type. The `LogEntryInfo` type in
/// `crate::types` is a simplified view for API responses.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, ts_rs::TS)]
pub struct LogEntry {
    /// Entry index (1-based).
    pub line_number: usize,
    /// Log level (TRACE, DEBUG, INFO, WARN, ERROR).
    pub level: String,
    /// Timestamp string.
    pub timestamp: Option<String>,
    /// The log message.
    pub message: String,
    /// Event type (event, span_enter, span_exit, span_new, span_close).
    pub event_type: String,
    /// Span name (if this is a span event).
    pub span_name: Option<String>,
    /// Indentation depth (number of parent spans).
    pub depth: usize,
    /// Additional fields (preserves structured JSON values).
    #[schemars(with = "std::collections::HashMap<String, serde_json::Value>")]
    #[ts(type = "Record<string, unknown>")]
    pub fields: HashMap<String, serde_json::Value>,
    /// Source file location (from tracing macro).
    pub file: Option<String>,
    /// Source line number (from tracing macro).
    pub source_line: Option<u32>,
    /// Panic file location (from panic info, points to actual assertion).
    pub panic_file: Option<String>,
    /// Panic line number.
    pub panic_line: Option<u32>,
    /// Parsed assertion diff (for failed assertions).
    pub assertion_diff: Option<AssertionDiff>,
    /// Stack trace (for panics).
    pub backtrace: Option<String>,
    /// Raw summary string.
    pub raw: String,
}

/// Conversion from full `LogEntry` to the simplified `LogEntryInfo` API type.
impl From<&LogEntry> for crate::types::LogEntryInfo {
    fn from(entry: &LogEntry) -> Self {
        Self {
            entry_number: entry.line_number,
            level: entry.level.clone(),
            timestamp: entry.timestamp.clone(),
            message: entry.message.clone(),
            event_type: entry.event_type.clone(),
            span_name: entry.span_name.clone(),
            depth: entry.depth,
            fields: serde_json::to_value(&entry.fields).unwrap_or_default(),
            source_file: entry.file.clone(),
            source_line: entry.source_line,
        }
    }
}

/// Raw JSON structure from tracing-subscriber.
#[derive(Debug, Deserialize)]
struct TracingJson {
    timestamp: Option<String>,
    level: Option<String>,
    fields: Option<serde_json::Value>,
    target: Option<String>,
    span: Option<SpanEntry>,
    spans: Option<Vec<SpanEntry>>,
    #[serde(rename = "filename")]
    file: Option<String>,
    #[serde(rename = "line_number")]
    line: Option<u32>,
}

#[derive(Debug, Deserialize)]
struct SpanInfo {
    name: Option<String>,
    #[serde(flatten)]
    fields: HashMap<String, serde_json::Value>,
}

/// Wrapper that deserializes from either a string or a SpanInfo object.
#[derive(Debug)]
struct SpanEntry(SpanInfo);

impl<'de> serde::Deserialize<'de> for SpanEntry {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(name) => Ok(SpanEntry(SpanInfo {
                name: Some(name),
                fields: HashMap::new(),
            })),
            serde_json::Value::Object(_) => {
                let info: SpanInfo =
                    serde_json::from_value(serde_json::Value::Object(
                        value.as_object().cloned().unwrap_or_default(),
                    ))
                    .map_err(serde::de::Error::custom)?;
                Ok(SpanEntry(info))
            },
            _ =>
                Err(serde::de::Error::custom("span must be a string or object")),
        }
    }
}

/// Parser for log files produced by a `tracing-subscriber` JSON writer.
pub struct LogParser;

impl LogParser {
    pub fn new() -> Self {
        Self
    }

    fn fields_object<'a>(
        &self,
        json: &'a TracingJson,
    ) -> Option<&'a serde_json::Map<String, serde_json::Value>> {
        json.fields.as_ref()?.as_object()
    }

    fn collect_entry_fields(
        &self,
        json: &TracingJson,
    ) -> HashMap<String, serde_json::Value> {
        let mut fields = HashMap::new();

        if let Some(obj) = self.fields_object(json) {
            for (key, value) in obj {
                if !matches!(
                    key.as_str(),
                    "message"
                        | "backtrace"
                        | "panic_file"
                        | "panic_line"
                        | "panic_column"
                ) {
                    fields.insert(key.clone(), value.clone());
                }
            }
        }

        if let Some(span) = &json.span {
            for (key, value) in &span.0.fields {
                if key != "name" {
                    fields.insert(key.clone(), value.clone());
                }
            }
        }

        fields
    }

    fn extract_panic_fields(
        &self,
        json: &TracingJson,
    ) -> (Option<String>, Option<u32>) {
        let Some(obj) = self.fields_object(json) else {
            return (None, None);
        };

        let panic_file = obj
            .get("panic_file")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string);
        let panic_line = obj
            .get("panic_line")
            .and_then(serde_json::Value::as_u64)
            .map(|line| line as u32);

        (panic_file, panic_line)
    }

    fn extract_message(
        &self,
        json: &TracingJson,
    ) -> String {
        self.fields_object(json)
            .and_then(|obj| obj.get("message"))
            .map(|value| match value {
                serde_json::Value::String(text) => strip_ansi_codes(text),
                other => strip_ansi_codes(&other.to_string()),
            })
            .unwrap_or_default()
    }

    fn extract_backtrace(
        &self,
        json: &TracingJson,
    ) -> Option<String> {
        self.fields_object(json)
            .and_then(|obj| obj.get("backtrace"))
            .map(|value| match value {
                serde_json::Value::String(text) => text.clone(),
                other => other.to_string(),
            })
    }

    fn detect_event_type(
        &self,
        message: &str,
        json: &TracingJson,
    ) -> String {
        if (message.contains("new") || message.contains("enter"))
            && json
                .span
                .as_ref()
                .and_then(|span| span.0.name.as_ref())
                .is_some()
        {
            return if message.contains("new") {
                "span_new".to_string()
            } else {
                "span_enter".to_string()
            };
        }

        if (message.contains("close") || message.contains("exit"))
            && json.span.is_some()
        {
            return "span_exit".to_string();
        }

        "event".to_string()
    }

    fn apply_message_fallback(
        &self,
        mut message: String,
        event_type: &mut String,
        json: &TracingJson,
    ) -> String {
        if !message.is_empty() {
            return message;
        }

        if let Some(name) =
            json.span.as_ref().and_then(|span| span.0.name.as_ref())
        {
            *event_type = "span_enter".to_string();
            message = format!("Span: {}", name);
        }

        if message.is_empty() {
            message =
                json.target.clone().unwrap_or_else(|| "Unknown".to_string());
        }

        message
    }

    /// Parse log content into structured entries.
    ///
    /// Handles both pretty-printed JSON (multi-line) and NDJSON formats.
    /// Uses serde_json's streaming deserializer to parse consecutive JSON objects.
    pub fn parse(
        &self,
        content: &str,
    ) -> Vec<LogEntry> {
        let mut entries = Vec::new();

        let stream = serde_json::Deserializer::from_str(content)
            .into_iter::<TracingJson>();

        for (index, result) in stream.enumerate() {
            let entry_num = index + 1;

            match result {
                Ok(json) => {
                    entries.push(self.json_to_entry(entry_num, &json));
                },
                Err(e) => {
                    entries.push(LogEntry {
                        line_number: entry_num,
                        level: "ERROR".to_string(),
                        timestamp: None,
                        message: format!("JSON parse error: {}", e),
                        event_type: "error".to_string(),
                        span_name: None,
                        depth: 0,
                        fields: HashMap::new(),
                        file: None,
                        source_line: None,
                        panic_file: None,
                        panic_line: None,
                        assertion_diff: None,
                        backtrace: None,
                        raw: format!("Parse error at entry {}", entry_num),
                    });
                    // Stop on parse errors to avoid cascading failures
                    break;
                },
            }
        }

        entries
    }

    fn json_to_entry(
        &self,
        line_number: usize,
        json: &TracingJson,
    ) -> LogEntry {
        let level = json.level.clone().unwrap_or_else(|| "INFO".to_string());

        let (message, event_type, backtrace) =
            self.extract_message_and_type(json);

        let span_name = json
            .span
            .as_ref()
            .and_then(|s| s.0.name.clone())
            .or_else(|| {
                json.spans
                    .as_ref()
                    .and_then(|spans| spans.last())
                    .and_then(|s| s.0.name.clone())
            });

        let depth = json.spans.as_ref().map(|s| s.len()).unwrap_or(0);
        let fields = self.collect_entry_fields(json);

        let file = json.file.clone();
        let source_line = json.line;
        let (mut panic_file, mut panic_line) = self.extract_panic_fields(json);

        if panic_file.is_none() && message.contains("panicked at") {
            if let Some((pf, pl, _col)) = parse_panic_location(&message) {
                panic_file = Some(pf);
                panic_line = Some(pl);
            }
        }

        let assertion_diff = parse_assertion_diff(&message);

        LogEntry {
            line_number,
            level: level.clone(),
            timestamp: json.timestamp.clone(),
            message: message.clone(),
            event_type,
            span_name,
            depth,
            fields,
            file,
            source_line,
            panic_file,
            panic_line,
            assertion_diff,
            backtrace,
            raw: format!("[{}] {}", level, message),
        }
    }

    fn extract_message_and_type(
        &self,
        json: &TracingJson,
    ) -> (String, String, Option<String>) {
        let mut event_type =
            self.detect_event_type(&self.extract_message(json), json);
        let message = self.apply_message_fallback(
            self.extract_message(json),
            &mut event_type,
            json,
        );
        let backtrace = self.extract_backtrace(json);

        (message, event_type, backtrace)
    }
}

impl Default for LogParser {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_event() {
        let json = r#"{
            "timestamp": "2026-03-14T00:55:30.028572Z",
            "level": "INFO",
            "fields": {
                "message": "test message",
                "some_field": "value"
            },
            "target": "test_target",
            "filename": "test.rs",
            "line_number": 42
        }"#;

        let parser = LogParser::new();
        let entries = parser.parse(json);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].level, "INFO");
        assert_eq!(entries[0].message, "test message");
        assert_eq!(entries[0].file.as_deref(), Some("test.rs"));
        assert_eq!(entries[0].source_line, Some(42));
        assert!(entries[0].fields.contains_key("some_field"));
    }

    #[test]
    fn test_parse_multiple_entries() {
        let json = r#"{"timestamp": "t1", "level": "INFO", "fields": {"message": "first"}}
{"timestamp": "t2", "level": "WARN", "fields": {"message": "second"}}"#;

        let parser = LogParser::new();
        let entries = parser.parse(json);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].message, "first");
        assert_eq!(entries[1].message, "second");
        assert_eq!(entries[1].level, "WARN");
    }

    #[test]
    fn test_parse_span_enter() {
        let parser = LogParser::new();
        let content = r#"{"timestamp":"2024-01-01T00:00:00.000000Z","level":"INFO","fields":{"message":"enter"},"target":"test","span":{"name":"my_function"}}"#;
        let entries = parser.parse(content);

        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        assert_eq!(entry.level, "INFO");
        assert_eq!(entry.event_type, "span_enter");
        assert_eq!(entry.span_name.as_deref(), Some("my_function"));
    }

    #[test]
    fn test_parse_span_close() {
        let parser = LogParser::new();
        let content = r#"{"timestamp":"2024-01-01T00:00:00.000000Z","level":"INFO","fields":{"message":"close"},"target":"test","span":{"name":"my_function"}}"#;
        let entries = parser.parse(content);

        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        assert_eq!(entry.level, "INFO");
        assert_eq!(entry.event_type, "span_exit");
        assert_eq!(entry.span_name.as_deref(), Some("my_function"));
    }

    #[test]
    fn test_calculate_depth() {
        let parser = LogParser::new();
        let entry1 =
            r#"{"level":"INFO","fields":{"message":"test"},"spans":[]}"#;
        let entry2 = r#"{"level":"INFO","fields":{"message":"test"},"spans":[{"name":"a"}]}"#;
        let entry3 = r#"{"level":"INFO","fields":{"message":"test"},"spans":[{"name":"a"},{"name":"b"}]}"#;

        let entries =
            parser.parse(&format!("{}\n{}\n{}", entry1, entry2, entry3));
        assert_eq!(entries[0].depth, 0);
        assert_eq!(entries[1].depth, 1);
        assert_eq!(entries[2].depth, 2);
    }

    #[test]
    fn test_strip_ansi_codes() {
        assert_eq!(strip_ansi_codes("\x1b[31mred\x1b[0m"), "red");
        assert_eq!(strip_ansi_codes("no codes"), "no codes");
    }

    #[test]
    fn test_parse_panic_location() {
        let msg = "panicked at src/main.rs:42:5: assertion failed";
        let result = parse_panic_location(msg);
        assert!(result.is_some());
        let (file, line, col) = result.unwrap();
        assert_eq!(file, "src/main.rs");
        assert_eq!(line, 42);
        assert_eq!(col, 5);
    }

    #[test]
    fn test_default_impl() {
        let parser = LogParser::default();
        let entries =
            parser.parse(r#"{"level":"DEBUG","fields":{"message":"hi"}}"#);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].message, "hi");
    }
}
